services:
  lndboss:
    build: .
    volumes:
      - ~/.bosgui:/home/node/.bosgui
      - /Users/nitesh/.polar/networks/1/volumes/lnd/alice/:/home/node/.lnd
    ports:
      - "8055:8055"
    environment:
      BOS_DATA_PATH: '/home/node/.bosgui'
      NODE_ENV: 'production'
      PORT: 8055
      BOS_DEFAULT_LND_SOCKET: "localhost:10001"
networks:
  default:
    name: 1_default
    external: true
