services:
  lndboss-backend:
    image: lndboss-backend
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ~/.bosgui/bosguidocker:/home/node/.bosgui
      - /Users/nitesh/.polar/networks/1/volumes/lnd/alice/:/home/node/.lnd
    environment:
      BACKEND_PORT: 8056
      BOS_DATA_PATH: "/home/node/.bosgui"
      NODE_ENV: "production"
    ports:
      - "8056:8056"

  lndboss-frontend:
    image: lndboss-frontend
    build:
      dockerfile: frontend.Dockerfile
    environment:
      NODE_ENV: "production"
      PORT: 8055
    ports:
      - "8055:8055"

networks:
  default:
    name: 1_default
    external: true
